# Generated by Django 6.1.1 on 2026-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                        ],
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["day_of_week"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="menuitem",
            name="unique_daily_menu_item",
        ),
        migrations.RemoveField(
            model_name="food",
            name="price",
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="foods",
            field=models.ManyToManyField(
                blank=True, related_name="daily_menus", to="menu.food"
            ),
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="vegetables",
            field=models.ManyToManyField(
                blank=True, related_name="daily_menus", to="menu.vegetable"
            ),
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
