# Generated by Django 6.1.1 on 2026-09-08 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_dailymenu_remove_menuitem_unique_daily_menu_item_and_more"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "confirmed", "completed"])
                ),
                fields=("user", "order_date"),
                name="one_active_order_per_user_per_day",
            ),
        ),
    ]
